name: Version
description: Run semantic-release and publish new version
inputs:
  branches: #Branches to release on
    description: 'Branches to release on'
    required: false
    default: 'main'
  dry-run: #Dry run
    description: 'Dry run'
    required: false
    default: 'false'
  github-token: #Github token
    description: 'Github token. Use a PAT token to trigger a release'
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
  commit-changelog: #Commit changelog
    description: |
      Commits changelog. 
      Warning, this will create a new commit and triggers 
      on "published" might not have correct ref to evaluate PRs'
    required: false
    default: 'false'
  npm-token: #NPM token
    description: 'NPM token'
    required: false
    default: ${{ secrets.NPM_TOKEN }}
  slack-webhook: #Slack webhook
    description: 'Slack webhook'
    required: false
    default: ${{ secrets.SLACK_RELEASE_BOT_WEBHOOK }}
  slack-channel: #Slack channel. Look ABOVE this to read how this might work https://github.com/juliuscc/semantic-release-slack-bot#slack-access-tokenchannel-usage
    description: 'Slack channel'
    required: false
runs:
  using: "composite"
  steps:
    - uses: cycjimmy/semantic-release-action@v3
      id: semantic
      with:
        extra_plugins: @semantic-release/changelog @semantic-release/git @semantic-release/exec semantic-release-slack-bot
        extends: @stacc/semantic-release-config
        branches: ${{ inputs.branches }}
        dry_run: ${{ inputs.dry-run }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
        SLACK_RELEASE_BOT_WEBHOOK: ${{ inputs.slack-webhook }}
        COMMIT_CHANGE_LOG: ${{ inputs.commit-changelog }}
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        SLACK_CHANNEL: ${{ inputs.slack-channel }}
outputs:
  new_release_published:
    value: ${{ steps.semantic.outputs.new_release_published }}
    description: 'Whether a new release was published'
  new_release_version:
    value: ${{ steps.semantic.outputs.new_release_version }}
    description: 'Version of the new release'
  new_release_major_version:
    value: ${{ steps.semantic.outputs.new_release_major_version }}
    description: 'Major version of the new release'
  new_release_minor_version:
    value: ${{ steps.semantic.outputs.new_release_minor_version }}
    description: 'Minor version of the new release'
  new_release_patch_version:
    value: ${{ steps.semantic.outputs.new_release_patch_version }}
    description: 'Patch version of the new release'
  new_release_channel:
    value: ${{ steps.semantic.outputs.new_release_channel }}
    description: 'The distribution channel on which the last release was initially made available (undefined for the default distribution channel).'
  new_release_notes:
    value: ${{ steps.semantic.outputs.new_release_notes }}
    description: 'The release notes for the new release.'
  last_release_version:
    value: ${{ steps.semantic.outputs.last_release_version }}
    description: 'Version of the previous release, if there was one.'
