name: Reusable workflow to provide evidence of a deployment

on:
  workflow_call:
    secrets:
      kosli-token:
        required: true
    inputs:
      pipeline:
        description: 'Name of the Kosli pipeline'
        required: true
        type: string
      environment:
        description: 'Name of the Kosli environment'
        required: true
        type: string
      sha256:
        type: string
        description: 'SHA256 of the published image'
        required: true

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: stacc/github-workflow-actions/actions/setup-kosli@main
        with:
          kosli-pipeline: ${{ inputs.pipeline }}
          kosli-token: ${{ secrets.kosli-token }}
      - name: Report deployment to registry in Kosli
        run: kosli pipeline deployment report --sha256 ${{ inputs.sha256 }} -e ${{ inputs.environment }} -p ${{ inputs.pipeline }}
