name: Reusable workflow to provide evidence of a deployment

on:
  workflow_call:
    secrets:
      kosli-token:
        required: true
      acr-username:
        required: true
      acr-password:
        required: true
    inputs:
      pipeline:
        description: 'Name of the Kosli pipeline'
        required: true
        type: string
      environment:
        description: 'Name of the Kosli environment'
        required: true
        type: string
      artifact:
        type: string
        description: 'Name of the published image'
        required: true
      acr-server:
        description: 'Name of the registry provider'
        required: false
        default: "stacc.azurecr.io"
        type: string
      description:
        description: 'Description of the deployment'
        required: false
        default: "Deployment"
        type: string

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: stacc/github-workflow-actions/actions/setup-kosli@main
        with:
          kosli-pipeline: ${{ inputs.pipeline }}
          kosli-token: ${{ secrets.kosli-token }}
      - name: Report deployment to registry in Kosli
        run: |
          kosli pipeline deployment report ${{ inputs.artifact }} -d ${{ description }} -e ${{ inputs.environment }} --registry-provider ${{ inputs.acr-server }} --registry-username ${{ secrets.acr-username }} --registry-password ${{ secrets.acr-password }}
